sonar.projectKey=nahushr_cinecrew-player
sonar.organization=nahushr
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=src,android/src/main/java,packages/react-native-vlc-media-player/ios/RCTVLCPlayer,packages/react-native-vlc-media-player/expo
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/.scannerwork/**,**/coverage/**,vendor/**,examples/**
sonar.coverage.exclusions=**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
