import { StyleSheet } from 'react-native';

export const createStyles = () => StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#07111e' },
  content: { width: '100%', maxWidth: 940, alignSelf: 'center', padding: 18, paddingBottom: 42, gap: 16 },
  eyebrow: { color: '#16c7d9', fontSize: 10, fontWeight: '900', letterSpacing: 1.8 },
  title: { color: '#f4f7fb', fontSize: 32, fontWeight: '900' },
  subtitle: { color: '#a9bbcf', fontSize: 14 },
  notice: { gap: 6, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: '#725f18', backgroundColor: '#282711' },
  noticeTitle: { color: '#ffe274', fontSize: 14, fontWeight: '900' },
  noticeBody: { color: '#e3dcae', fontSize: 12, lineHeight: 18 },
  section: { gap: 10 },
  sectionTitle: { color: '#f4f7fb', fontSize: 16, fontWeight: '800' },
  chipList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 22, borderWidth: 1, borderColor: '#29415d', backgroundColor: '#12243a' },
  chipSelected: { borderColor: '#16c7d9', backgroundColor: '#087f91' },
  chipText: { color: '#d3deeb', fontSize: 12, fontWeight: '800' },
  chipTextSelected: { color: '#fff' },
  card: { backgroundColor: '#0d1a2a', borderColor: '#203650', borderWidth: 1, padding: 14, borderRadius: 16, gap: 12 },
  input: { color: '#f3f7fc', backgroundColor: '#07111e', borderColor: '#29415d', borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12 },
  buttonRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  action: { alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 22, borderWidth: 1, borderColor: '#29415d', backgroundColor: '#12243a' },
  actionPrimary: { borderColor: '#16c7d9', backgroundColor: '#087f91' },
  actionText: { color: '#f8fbff', fontSize: 13, fontWeight: '800' },
  optionRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  optionText: { color: '#edf6ff', fontSize: 13, fontWeight: '700' },
  statusCard: { backgroundColor: '#0d1a2a', borderWidth: 1, borderColor: '#203650', borderRadius: 14, padding: 14, gap: 6 },
  statusHeading: { color: '#16c7d9', fontSize: 10, fontWeight: '900', letterSpacing: 1.4 },
  statusText: { color: '#f4f7fb', fontSize: 13, fontWeight: '700' },
  url: { color: '#a9bbcf', fontSize: 10, lineHeight: 15 },
  playerCard: { overflow: 'hidden', borderRadius: 16, borderWidth: 1, borderColor: '#203650', backgroundColor: '#0d1a2a', padding: 12, gap: 10 },
  footnote: { color: '#91a4bb', fontSize: 11, lineHeight: 17 },
});
