import { StyleSheet } from 'react-native';
import { isWeb } from '../../../utils/runtimePlatform';

export const mediaPlayerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  playerHost: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 99999,
    elevation: 99999,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  playerHostFullscreen: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
    zIndex: 99999,
    elevation: 99999,
  },
  fullscreenPlayerContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
    position: 'relative',
    overflow: 'hidden',
  },
  mediaFrame: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  inlinePlayerContainer: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: '#000',
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  electronFullscreenHost: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
    borderRadius: 0,
    backgroundColor: '#000',
    zIndex: 100000,
    overflow: 'hidden',
  },
  boundedInlinePlayerContent: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 'auto',
    height: 'auto',
    flex: 1,
  },
  inlineVideoStage: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    borderRadius: 14,
    position: 'relative',
  },
  playerHostInline: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: null,
    bottom: null,
    backgroundColor: '#000',
    borderRadius: 14,
    overflow: 'hidden',
    zIndex: 120,
    elevation: 0,
  },
  playerHostWeb: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 100000,
    overflow: 'hidden',
  },
  videoContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inlinePreviewChrome: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    padding: 10,
    zIndex: 6,
  },
  inlinePreviewTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    zIndex: 4,
  },
  inlinePreviewCenterControls: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
  },
  inlinePreviewCenterButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 2,
    backgroundColor: 'rgba(12, 18, 28, 0.76)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.82)',
  },
  inlineLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(183, 40, 47, 0.92)',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 7,
  },
  inlineLiveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#FFF',
  },
  inlineLiveText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  inlinePreviewIconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: 'rgba(12, 18, 28, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  inlinePreviewBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    zIndex: 4,
  },
  inlinePreviewActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inlinePreviewTitle: {
    flex: 1,
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
  },
  inlineChatButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(12, 18, 28, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 16,
  },
  inlineChatButtonText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
  },
  inlinePreviewLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  inlinePreviewLoadingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 24,
    backgroundColor: 'rgba(4, 10, 18, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
  },
  inlinePreviewLoadingText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
  },
  inlinePreviewError: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.55)',
    zIndex: 8,
  },
  inlinePreviewErrorText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
  },
  videoWrapFullscreen: {
    width: '100%',
    height: '100%',
    flex: 1,
  },
  video: {
    width: '100%',
    height: '100%',
  },
  controlsShell: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    zIndex: 65,
    elevation: 65,
  },
  controlsPanel: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
  },
  brightnessDimOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
    zIndex: 15,
    elevation: 15,
  },
  zoomBadge: {
    position: 'absolute',
    top: 30,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    zIndex: 9999,
  },
  zoomBadgeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  seekRippleOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9998,
  },
  seekRippleLeft: {
    left: 0,
    borderTopRightRadius: 200,
    borderBottomRightRadius: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  seekRippleRight: {
    right: 0,
    borderTopLeftRadius: 200,
    borderBottomLeftRadius: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  seekRippleCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 28,
  },
  seekRippleText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: 4,
  },
  gestureCatcher: {
    // Keep the touch layer visually transparent and unelevated. Elevating an
    // otherwise transparent React Native view over VLC's Android surface can
    // leave rectangular composition artifacts when playback controls hide.
    backgroundColor: 'transparent',
    zIndex: 50,
    ...(isWeb()
      ? {
          touchAction: 'none',
          userSelect: 'none',
        }
      : {}),
  },
  loadingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    zIndex: 999,
    elevation: 999,
  },
  loadingText: {
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  centeredOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    gap: 12,
    zIndex: 100,
  },
  errorTitle: {
    color: '#FFF',
  },
  errorMsg: {
    color: '#CCC',
    textAlign: 'center',
  },
  errorBtn: {
    marginTop: 8,
    backgroundColor: '#E53935',
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  errorBtnText: {
    color: '#FFF',
  },
});
